In [2]:
import torch


In [3]:
x = torch.arange(4)

In [4]:
x

tensor([0, 1, 2, 3])

In [ ]:
x = x.float()
x.requires_grad=True


In [24]:
x.grad


tensor([0., 1., 4., 9.])

In [25]:
y = 2 * torch.dot(x,x)#y = 2x^2,对x求导为4x，所以1变化1，y变化4，2变化1，y变化8

In [26]:
y

tensor(28., grad_fn=<MulBackward0>)

In [27]:
y.backward()
x.grad #

tensor([ 0.,  5., 12., 21.])

In [29]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad



tensor([1., 1., 1., 1.])

In [ ]:
x.grad.zero_()
y = x*x
u = y.detach()#u一个常数
z = u*x
z.sum().backward()#对 z 的和反向传播。由于 u 常数，∂z/∂x = u，所以梯度直接拷贝 u。
x.grad == u


tensor([True, True, True, True])